import type { ComplianceReport } from "../types";
import { formatClause, formatDate, formatTimestamp } from "../lib/status";
import { SourceCallout } from "./RuleDrawer";
import { StatusBadge } from "./StatusBadge";

interface Props {
  report: ComplianceReport | null;
  loading: boolean;
  asOf: string;
  onRefresh: () => void;
  onDownload: () => void;
  downloadBusy?: boolean;
}

export function ReportPreview({
  report,
  loading,
  asOf,
  onRefresh,
  onDownload,
  downloadBusy = false,
}: Props) {
  return (
    <div className="space-y-4">
      <div className="rounded-card border border-gold/20 border-l-4 border-l-gold bg-gold/[0.05] px-5 py-4">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="label-caps text-gold">Evidence Pack</div>
            <h2 className="mt-1 font-serif text-xl text-ink">
              In-app compliance report preview
            </h2>
            <p className="mt-1 max-w-3xl text-sm text-muted">
              Preview the structured report before export: summary counts, breach
              citations, amendment impact, and officer sign-off state for the selected
              as-of date.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={onRefresh}
              disabled={loading}
              className="rounded border border-gold/30 px-3 py-2 text-sm font-medium text-gold transition-colors hover:bg-gold/10 disabled:opacity-50"
            >
              {loading ? "Loading…" : "Refresh preview"}
            </button>
            <button
              onClick={onDownload}
              disabled={downloadBusy || loading}
              className="rounded border border-gold bg-gold px-4 py-2 text-sm font-semibold text-canvas transition-colors hover:bg-gold-400 disabled:opacity-50"
            >
              {downloadBusy ? "Generating PDF…" : "Download PDF"}
            </button>
          </div>
        </div>
      </div>

      {!report ? (
        <div className="card px-5 py-12 text-center text-sm text-muted">
          {loading
            ? "Preparing compliance report preview…"
            : `Load the report preview for ${formatDate(asOf)} to inspect the evidence pack.`}
        </div>
      ) : (
        <>
          <div className="grid gap-4 md:grid-cols-5">
            <Metric label="Compliant" value={report.summary.compliant} tone="ok" />
            <Metric label="Breach" value={report.summary.breach} tone="warn" />
            <Metric label="N/A" value={report.summary.not_applicable} />
            <Metric label="Signed off" value={report.summary.signoff_reviewed} />
            <Metric label="Pending review" value={report.summary.signoff_pending} />
          </div>

          <div className="card px-5 py-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <h3 className="font-serif text-lg text-ink">Report header</h3>
                <p className="text-xs text-muted">
                  As of {formatDate(report.as_of)} · generated by {report.generated_by} ·{" "}
                  {formatTimestamp(report.generated_at)}
                </p>
              </div>
              <div className="rounded border border-hair bg-canvas px-3 py-2 text-xs text-muted">
                Engine <span className="font-mono text-ink">{report.engine.name}</span> · ruleset{" "}
                <span className="font-mono text-ink">{report.engine.ruleset}</span>
              </div>
            </div>
          </div>

          {report.regulatory_delta && (
            <div className="card px-5 py-4">
              <h3 className="font-serif text-lg text-ink">Amendment impact in report</h3>
              <p className="mt-1 text-sm text-muted">
                Window {formatDate(report.regulatory_delta.from_as_of)} to{" "}
                {formatDate(report.regulatory_delta.to_as_of)} · {report.regulatory_delta.summary.total_transitions}{" "}
                posture transition(s) · {report.regulatory_delta.summary.firms_newly_flagged} newly
                flagged firm(s)
              </p>
              <div className="mt-3 space-y-3">
                {report.regulatory_delta.rule_changes.map((change) => (
                  <div
                    key={change.old.rule_id}
                    className="rounded border border-hair bg-canvas px-4 py-3"
                  >
                    <div className="text-sm font-medium text-ink">
                      {formatClause(change.old.clause_id)} superseded by{" "}
                      {formatClause(change.new.clause_id)}
                    </div>
                    <div className="mt-1 text-xs text-muted">
                      {change.old.value_summary} {"->"} {change.new.value_summary}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="grid gap-4 xl:grid-cols-[1.1fr_0.9fr]">
            <div className="card px-5 py-4">
              <h3 className="font-serif text-lg text-ink">Breach citations</h3>
              <div className="mt-3 space-y-4">
                {report.breaches.length === 0 ? (
                  <div className="rounded border border-hair bg-canvas px-4 py-6 text-sm text-muted">
                    No breaches in the current report.
                  </div>
                ) : (
                  report.breaches.map((breach) => (
                    <div key={`${breach.firm_id}-${breach.rule_id}`} className="rounded border border-hair bg-canvas px-4 py-4">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-sm font-medium text-ink">{breach.firm_name}</span>
                        <StatusBadge status="breach" />
                        <span className="font-mono text-[11px] text-muted">
                          {formatClause(breach.clause_id)}
                        </span>
                      </div>
                      <p className="mt-2 text-sm text-ink">
                        {breach.plain_label ?? breach.plain_description}
                      </p>
                      {breach.detail?.actual !== undefined && (
                        <div className="mt-2 text-xs text-muted">
                          Actual: <span className="font-mono text-ink">{stringify(breach.detail.actual)}</span>
                          {" · "}
                          Expected: <span className="font-mono text-ink">{stringify(breach.detail.expected)}</span>
                        </div>
                      )}
                      {breach.required_action && (
                        <div className="mt-2 rounded border border-hair bg-surface px-3 py-2 text-xs text-ink">
                          Recommended action: {breach.required_action}
                        </div>
                      )}
                      {breach.source_text_span && (
                        <div className="mt-3">
                          <SourceCallout
                            text={breach.source_text_span}
                            clause={formatClause(breach.clause_id)}
                            circular={report.circular.id}
                          />
                        </div>
                      )}
                    </div>
                  ))
                )}
              </div>
            </div>

            <div className="space-y-4">
              <div className="card px-5 py-4">
                <h3 className="font-serif text-lg text-ink">Officer sign-off state</h3>
                <p className="mt-1 text-sm text-muted">
                  {report.officer_signoff.reviewed_count} reviewed ·{" "}
                  {report.officer_signoff.pending_count} pending
                </p>
                <div className="mt-3 space-y-3">
                  {report.officer_signoff.log.length === 0 ? (
                    <div className="rounded border border-hair bg-canvas px-4 py-6 text-sm text-muted">
                      No officer review tasks recorded for this as-of date yet.
                    </div>
                  ) : (
                    report.officer_signoff.log.map((item) => (
                      <div key={item.task_id} className="rounded border border-hair bg-canvas px-4 py-3">
                        <div className="flex items-center justify-between gap-3">
                          <div className="text-sm font-medium text-ink">{item.title}</div>
                          <StatusBadge
                            status={item.status === "reviewed" ? "compliant" : "breach"}
                          />
                        </div>
                        <div className="mt-1 text-xs text-muted">
                          {item.firm_name} · {formatClause(item.clause_id)}
                        </div>
                        <div className="mt-2 text-xs text-ink">
                          Recommended action: {item.recommended_action}
                        </div>
                        {item.reviewed_by && (
                          <div className="mt-2 text-[11px] text-muted">
                            Signed off by {item.reviewed_by} · {formatTimestamp(item.reviewed_at)}
                          </div>
                        )}
                      </div>
                    ))
                  )}
                </div>
              </div>

              <div className="card px-5 py-4">
                <h3 className="font-serif text-lg text-ink">Circular metadata</h3>
                <div className="mt-3 space-y-2 text-sm text-muted">
                  <div>
                    Circular ID: <span className="font-mono text-ink">{report.circular.id}</span>
                  </div>
                  <div>Title: <span className="text-ink">{report.circular.title}</span></div>
                  <div>Issued: <span className="text-ink">{formatDate(report.circular.issued)}</span></div>
                  <div className="pt-2 text-xs">{report.disclaimer}</div>
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function Metric({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone?: "ok" | "warn";
}) {
  return (
    <div className="card-muted px-4 py-3">
      <div
        className={`font-mono text-2xl font-semibold tnum ${
          tone === "ok" ? "text-compliant-text" : tone === "warn" ? "text-breach" : "text-ink"
        }`}
      >
        {value}
      </div>
      <div className="text-xs text-muted">{label}</div>
    </div>
  );
}

function stringify(value: unknown): string {
  if (value == null) return "—";
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}
